app = "collab-editor"
primary_region = "cdg"

[env]
  PORT = "3000"
  SITE_URL = "collab-editor.fly.dev"
  VITE_SITE_URL = "collab-editor.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
