# fly.toml app configuration file generated for collab-editor on 2023-06-08T15:32:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "collab-editor"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  NODE_ENV = "production"
  PORT = 3000
